### ISSUE TITLE
Error: Query.node field config must be an object

### ISSUE THREAD

**Issue by jamesallain** [jonirrings/react-stack#1]
Hello Jonir,

Your RGR stack is the best I've ever seen. I'm trying to use it to help me learn Relay.  I'm getting 
"Error: Query.node field config must be an object" when I run "babel-node tools/run updateSchema". Can you help me?

Thanks a lot,
James

**Comment by jonirrings** [comment]
@jamesallain pls `git checkout 2567784b28697cbf149b57b8918c327d65a4a5d9`, the latter commit are not fixed because of the delayed update of the orginal relay-subscription npm packages which I used for subscription enhancement for relay.
I'm working on an apollo branch for sake of that apollo-stack supports subscription.
Later when graphql&relay officially support subscription I will remove the relay-subscription npm packages and implement it in an official way.
Sorry for my late reply.

**Comment by jamesallain** [comment]
Thanks Jonir! I'm going to give apollo a shot too. It's hard to find good examples of relay. There are not many like yours. Looking forward to seeing your apollo-stack. Good luck! 
James

**Comment by jonirrings** [comment]
@jamesallain hi, james, I am fixing the error and removing subscription. the problem `updateSchema` reported seems to be cause by the incompatibility of `graphql@0.9.3` and `graphql-relay@0.5.1`, and to rewrite the `graphql-relay` may solve the problem.

**Comment by jamesallain** [comment]
Hey Jonir! Thanks for update and congrats on the job offer. Their website looks pretty cool.  I still get the same error too. I'm really liking apollo so far. The subscriptions work well.

**Comment by jamesallain** [comment]
It looks like you're switching to Relay Modern. I just found out it was released and read all the docs today. It's definitely easier than Relay Classic. Do you need any help? I can migrate some components, queries, and mutations.  
James

**Comment by jonirrings** [comment]
@jamesallain I'm reading the doc too. 
I'm writing the wiki and roadmap for this repo.  
have a look and make some suggestion, so we can make this stack better for those who study GraphQL
it is grateful of you, if you help to build/migreate the stack.
let's just keep in touch, you can contact me by email or just by this issue.
it is difficult for me is to build a Relay-Enhanced GraphQL server along with the database specific features. 
b/c not skilled at DataBase:joy:
I'm not a native English speaker, if there are any typo or inaccurate word, can you give hint~

Thanks
Jonir

**Comment by jamesallain** [comment]
Hey Jonir, I'm actually much better with databases :) I prefer postgresql over mongo.  We could use [Sequelize](http://docs.sequelizejs.com/en/v3/). It would allow people to use whatever relational db they are the most comfortable with. 

Cassandra is really complex. I think it would be better to do that later.

I will work on the wiki whenever you're finished to make it more "western" :)

**Comment by jonirrings** [comment]
@jamesallain Okay, let's get start from PostgreSQL. you're the collaborator now, just do what you like.
How about open a new issue or use the github ·Project· feature to discuss and track our progress?

**Comment by jamesallain** [comment]
Yeah, I think the github Project will work. Would you mind starting it and I'll follow your lead?

**Comment by jonirrings** [comment]
I meet this error again, it arised after I run `yarn upgrade`, maybe we shall specify the `must match` style `semver` for each npm package, at least for `babel related package`.
so, the problem may be related with `node version` or `babel related version`

**Comment by jonirrings** [comment]
@jamesallain there is another GraphQL build problem you might encounter:
`Root.node field type must be Output Type but got: Node`

it is caused by the graphql-relay having installed another graphql in its `node_modules`.
 solution is:
just install `graphql` before `graphql-relay`
```
yarn remove graphql-relay
yarn add graphql
yarn add graphql-relay
```

**Comment by jamesallain** [comment]
Thanks Jon. I haven't had a chance to look at it much the past few weeks. Hopefully, I can check it out this weekend.  I've been trying to get relay to work with react native. At this point, I don't think it's possible on windows. I'm going to switch back to linux tomorrow.
