### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by alexhawkins** [jonirrings/react-stack#2]
This is awesome. Keep up the good work.  I really like how you've organized everything. Well done. Would love to see subscriptions and data loader implemented and eventually porting this to relay 2. Would be cool to set up a version using Cassandra as well. That's what we're using. You can check out what we built with React, Relay 1, GraphQL and Cassandra microservices here : https://beta.onehopewine.com/shop/wine/wine. It's basically an e-commerce platform from scratch.

Actually, we are hiring fullstack software engineers with your background right now!!! Would you be interested in working with us? Good salary, good equity. Company is a wine company so you get unlimited free wine as well. Also backed by founders of Palantir, Addepar, Top Golf, 8VC, John Elway etc... to name a few. So the equity you get upon joining would def be worth something. I believe our total compensation package is on par with Google and Facebook. Probably a bit better.

Email me at alex@onehopewine.com and I would respond as quickly as possible.

**Comment by jonirrings** [comment]
@alexhawkins thanks, alex.
replid to you by email. 
Your site is pretty cool with an elegant design.

**Comment by alexhawkins** [comment]
Actually could you resend your email to me at alexhawkins.me@gmail.com? That email address I posted is not working for whatever reason. Thanks
